export const ACTION_TYPE = 'ACTION_TYPE';
export const FETCH_PLANNERS = 'FETCH_PLANNERS';
export const FETCH_ANNOUNCEMENT = 'FETCH_ANNOUNCEMENT';
export const FETCH_FIREBASE_ANNOUNCEMENT = 'FETCH_FIREBASE_ANNOUNCEMENT';
export const APP_LOGIN = 'APP_LOGINS';
export const ADD_PLANNER = 'ADD_PLANNER';
export const FETCH_STUDENTS_LIST = 'FETCH_STUDENTS_LIST';

export const FETCH_GOOGLE_PLANNER = 'FETCH_GOOGLE_PLANNER';
export const FETCH_MICROSOFT_PLANNER = 'FETCH_MICROSOFT_PLANNER';
export const FETCH_FIREBASE_PLANNER = 'FETCH_FIREBASE_PLANNER';

export const CREATE_PLANNER_CALLBACK = 'CREATE_PLANNER_CALLBACK';

export const UPLOAD_FILES_GOOGLE_DRIVE = 'UPLOAD_FILES_GOOGLE_DRIVE';
export const GRANT_GOOGLE_DRIVE_PERMISSION = 'GRANT_GOOGLE_DRIVE_PERMISSION';

export const CREATE_GOOGLE_PLANNER = 'CREATE_GOOGLE_PLANNER';
export const CREATE_MICROSOFT_PLANNER = 'CREATE_MICROSOFT_PLANNER';
export const CREATE_FIREBASE_PLANNER = 'CREATE_FIREBASE_PLANNER';